# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=11)),
                ('birth_date', models.DateTimeField()),
                ('first_session_date', models.DateTimeField(auto_now=True)),
                ('sex', models.BooleanField()),
                ('age', models.IntegerField()),
                ('skill', models.IntegerField()),
                ('profile', models.CharField(max_length=200)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_athlete.fields')),
            ],
        ),
    ]
