# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_athlete', '0002_auto_20180730_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other')], max_length=1),
        ),
    ]
