# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_athlete', '0004_auto_20180730_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='skill',
            field=models.CharField(choices=[('\u200c\u200cB', 'beginner'), ('E', 'elementary'), ('P', 'professional')], max_length=1),
        ),
    ]
