# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-30 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_athlete', '0005_auto_20180730_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.TextField(max_length=200),
        ),
    ]
