# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-01 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_athlete', '0006_auto_20180730_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_times',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_time', models.CharField(choices=[('1', '8 - 10'), ('2', '10 - 12'), ('3', '16 - 18'), ('4', '18 - 20')], max_length=1)),
            ],
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='member',
        ),
        migrations.AddField(
            model_name='fields',
            name='class_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web_athlete.class_times'),
            preserve_default=False,
        ),
    ]
